/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/WawaOffice.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from 'gsap'
import { useFrame } from '@react-three/fiber'

const FLOOR_HIGHT = 2.3 ;
const NB_FLOOR = 3 ; 

const  Office = (props)=> {
  const { nodes, materials } = useGLTF('./models/WawaOffice.glb')
  const GroupRef = useRef() // for the main group container 
  const tl = useRef()   // control the timeline for animation

  const AtticRef = useRef() //   the las group of mesh 
  const libRef = useRef() // the second group of mesh 
  const scroll = useScroll()


  useFrame(()=>{
    tl.current.seek(scroll.offset * tl.current.duration())
  })

  useEffect(()=>{

    tl.current = gsap.timeline()
    // animating the scroll 
    tl.current.to(GroupRef.current.position,{
      duration : 2,
      y : -FLOOR_HIGHT * (NB_FLOOR -1)
    },0
    )

    // animating the lib group 
    tl.current.from(libRef.current.position , {
      duration  :0.5 ,
      x : -2
    },0.5)

    // animate the Attic

    tl.current.from(AtticRef.current.position ,{
      duration  : 1.5 ,
      y : 2 
    } , 0)

    tl.current.from(AtticRef.current.position ,{
      duration  : 0.5 ,
      z : -2 
    } , 1.5)

  },[])

  return (
    <group {...props} dispose={null} ref={GroupRef}>


      <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
      <group position={[0, 2.114, -2.23]}>
        <group ref={libRef}>
          <mesh geometry={nodes['02_library'].geometry} material={materials['02']}  />
        </group>
      </group>
      
      <group position={[-1.97, 4.227, -2.199]}>
        <group ref={AtticRef}>
          <mesh geometry={nodes['03_attic'].geometry} material={materials['03']}  />
        </group>
      </group>

    </group>
  )
}

useGLTF.preload('./models/WawaOffice.glb')

export default Office